const router = require("express").Router();
const pool = require("./db");
const PDFDocument = require("pdfkit");

router.get("/:id", async (req, res) => {
    try {
        const { id } = req.params;

        const todo = await pool.query(
            `SELECT 
                t.*, 
                u1.username AS created_by, 
                u2.username AS updated_by
            FROM todo t
            LEFT JOIN users u1 ON t.created_by = u1.user_id
            LEFT JOIN users u2 ON t.updated_by = u2.user_id
            WHERE t.todo_id = $1`,
            [id]
        );

        if (todo.rows.length === 0) {
            return res.status(404).json({ error: "Todo not found" });
        }

        const data = todo.rows[0];

        // --- Headers MUST come before piping ---
        res.setHeader("Content-Type", "application/pdf");
        res.setHeader(
            "Content-Disposition",
            `attachment; filename=todo_${id}.pdf`
        );

        // Create PDF
        const doc = new PDFDocument();
        doc.pipe(res);  // <--- MISSING IN YOUR CODE

        // Title
        doc.fontSize(20).text("Todo Details", { underline: true, align: "center" });
        doc.moveDown(2);

        // Table positions
        let startX = 50;
        let startY = 120;
        let rowHeight = 30;
        let col1Width = 150;
        let col2Width = 350;

        // Header row
        doc.rect(startX, startY, col1Width + col2Width, rowHeight).stroke();
        doc.fontSize(14).font("Helvetica-Bold")
            .text("Field", startX + 10, startY + 8)
            .text("Value", startX + col1Width + 10, startY + 8);

        startY += rowHeight;

        // Row function
    function addRow(label, value) {
            doc.fontSize(12).font("Helvetica");
            doc.rect(startX, startY, col1Width + col2Width, rowHeight).stroke();
            doc.text(label, startX + 10, startY + 8);
            doc.text(String(value), startX + col1Width + 10, startY + 8);
            startY += rowHeight;
        }

        // Add rows
        addRow("Description", data.description);
        addRow("Amount", data.amount);
        addRow("Created At", data.created_at);
        addRow("Updated At", data.updated_at);
        addRow("Created By", data.created_by);
        addRow("Updated By", data.updated_by);

        // Footer
        doc.moveDown(2);
        doc.fontSize(10).text("Report generated by Todo App",startX + 10, startY + 8, { align: "center" });
        doc.text(`Generated on: ${new Date().toLocaleString()}`, { align: "center" });
        doc.text()

        doc.end();

    } catch (err) {
        console.error("PDF ERROR:", err);
        res.status(500).json({ error: "Server error" });
    }
});

module.exports = router